In [1]:
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score

In [2]:
df = pd.read_csv('sleep.csv')

In [3]:
df.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea


Столбцы набора данных:  
- ID человека: идентификатор для каждого человека.  
- Пол: пол человека (мужчина/женщина).  
- Возраст: возраст человека в годах.  
- Род занятий: род занятий или профессия человека.  
- Продолжительность сна (часы): количество часов, которые человек спит в день.  
- Качество сна (шкала: 1-10): субъективная оценка качества сна в диапазоне от 1 до 10.  
- Уровень физической активности (минут/день): количество минут, в течение которых человек занимается физической активностью ежедневно.  
- Уровень стресса (шкала: 1-10): субъективная оценка уровня стресса, испытываемого человеком, в диапазоне от 1 до 10.  
- Категория ИМТ: категория индекса массы тела человека (например, недостаточный вес, нормальный вес, избыточный вес).  
- Артериальное давление (систолическое/диастолическое): измерение артериального давления человека, указанное как систолическое давление над диастолическим давлением.  
- Частота сердечных сокращений (уд/мин): частота сердечных сокращений человека в состоянии покоя в ударах в минуту.  
- Ежедневные шаги: количество шагов, которые человек делает за день.  
- Нарушение сна: наличие или отсутствие нарушения сна у человека (отсутствует, бессонница, апноэ во сне).

### **Выделим и предобработаем целевую переменную: нарушение сна**

In [4]:
df['Sleep Disorder'].unique()

array([nan, 'Sleep Apnea', 'Insomnia'], dtype=object)

**Заменим nan на 'doesn't have'**

In [5]:
df['Sleep Disorder'] = df['Sleep Disorder'].fillna("doesn't have")
df['Sleep Disorder'].unique()

array(["doesn't have", 'Sleep Apnea', 'Insomnia'], dtype=object)

In [6]:
sleep_dic = {'Insomnia': 0, "doesn't have":1, 'Sleep Apnea':2}
df['Sleep Disorder'] = df['Sleep Disorder'].map(sleep_dic)

In [7]:
Y = df['Sleep Disorder']
df = df.drop('Sleep Disorder', axis=1)

### **Предобработаю данные**

**Удалю незначащую колокнку с айди и преобразую гендер к бинарному числовому, а не текстовому виду**

In [8]:
df = df.drop('Person ID', axis=1)

In [9]:
df['Gender'] = df['Gender'].map({"Male":0, "Female":1})

In [10]:
df.head()

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps
0,0,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200
1,0,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000
2,0,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000
3,0,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000
4,0,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000

**Разобью возраст на категории по 5 лет, тк идейно, что 23, что 24. Разницы большой нет (влияет не возраст в пределах 5 лет, а показатели организма)**

In [11]:
print(df['Age'].min(), df['Age'].max())

27 59

In [12]:
groups = []
for i in range(df['Age'].min() - 1, df['Age'].max() + 5, 5):
    groups.append(i)
groups_cut = pd.cut(df['Age'].values, groups)
df['Age'] = groups_cut.codes

In [13]:
print(df['Age'].min(), df['Age'].max())

0 6

In [14]:
df.head()

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps
0,0,0,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200
1,0,0,Doctor,6.2,6,60,8,Normal,125/80,75,10000
2,0,0,Doctor,6.2,6,60,8,Normal,125/80,75,10000
3,0,0,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000
4,0,0,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000

In [15]:
df['Occupation'].unique()

array(['Software Engineer', 'Doctor', 'Sales Representative', 'Teacher',
       'Nurse', 'Engineer', 'Accountant', 'Scientist', 'Lawyer',
       'Salesperson', 'Manager'], dtype=object)

**Нельзя как-то эмпирически разделить эти профессии однозначно, поэтому воспользуюсь просто лейбл декодером**

In [16]:

le = LabelEncoder()
le.fit(df['Occupation'].unique())
le.classes_

array(['Accountant', 'Doctor', 'Engineer', 'Lawyer', 'Manager', 'Nurse',
       'Sales Representative', 'Salesperson', 'Scientist',
       'Software Engineer', 'Teacher'], dtype=object)

In [17]:
df['Occupation'] = le.transform(df['Occupation'])

In [18]:
df.head()

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps
0,0,0,9,6.1,6,42,6,Overweight,126/83,77,4200
1,0,0,1,6.2,6,60,8,Normal,125/80,75,10000
2,0,0,1,6.2,6,60,8,Normal,125/80,75,10000
3,0,0,6,5.9,4,30,8,Obese,140/90,85,3000
4,0,0,6,5.9,4,30,8,Obese,140/90,85,3000

**Разобьем сон на группы с ходом 0.5 (фазы сна)**

In [19]:
print(df['Sleep Duration'].min(), df['Sleep Duration'].max())

5.8 8.5

In [20]:
df['Sleep Duration'] = df['Sleep Duration'] * 10

In [21]:
groups = []
for i in range(54, 90, 5):
    groups.append(i)
groups_cut = pd.cut(df['Sleep Duration'].values, groups)
df['Sleep Duration'] = groups_cut.codes

In [22]:
df.head()

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps
0,0,0,9,1,6,42,6,Overweight,126/83,77,4200
1,0,0,1,1,6,60,8,Normal,125/80,75,10000
2,0,0,1,1,6,60,8,Normal,125/80,75,10000
3,0,0,6,0,4,30,8,Obese,140/90,85,3000
4,0,0,6,0,4,30,8,Obese,140/90,85,3000

**Закодирую Категория ИМТ**

In [23]:
le2 = LabelEncoder()
le2.fit(df['BMI Category'].unique())
df['BMI Category'] = le2.transform(df['BMI Category'])

In [24]:
df.head()

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps
0,0,0,9,1,6,42,6,3,126/83,77,4200
1,0,0,1,1,6,60,8,0,125/80,75,10000
2,0,0,1,1,6,60,8,0,125/80,75,10000
3,0,0,6,0,4,30,8,2,140/90,85,3000
4,0,0,6,0,4,30,8,2,140/90,85,3000

**Предобработаю давление**

In [25]:
df[['Systolic', 'Diastolic']] = df['Blood Pressure'].str.split('/', expand=True)

In [26]:
df.head()

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Systolic,Diastolic
0,0,0,9,1,6,42,6,3,126/83,77,4200,126,83
1,0,0,1,1,6,60,8,0,125/80,75,10000,125,80
2,0,0,1,1,6,60,8,0,125/80,75,10000,125,80
3,0,0,6,0,4,30,8,2,140/90,85,3000,140,90
4,0,0,6,0,4,30,8,2,140/90,85,3000,140,90

In [27]:
df['Systolic'] = df['Systolic'].astype(int)
df['Diastolic'] = df['Diastolic'].astype(int)

In [28]:
def determine_pressure_status(row):
    systolic = row['Systolic']
    diastolic = row['Diastolic']
    if systolic < 90 or diastolic < 60:
        return -1  # Пониженное давление
    elif systolic > 120 or diastolic > 80:
        return 1   # Повышенное давление
    else:
        return 0   # Нормальное давление
df['PressureStatus'] = df.apply(determine_pressure_status, axis=1)

In [29]:
df = df.drop(['Blood Pressure', 'Systolic', 'Diastolic'], axis=1)

In [30]:
df['Daily Steps'].unique()

array([ 4200, 10000,  3000,  3500,  8000,  4000,  4100,  6800,  5000,
        7000,  5500,  5200,  5600,  3300,  4800,  7500,  7300,  6200,
        6000,  3700])

In [31]:
df.head()

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Heart Rate,Daily Steps,PressureStatus
0,0,0,9,1,6,42,6,3,77,4200,1
1,0,0,1,1,6,60,8,0,75,10000,1
2,0,0,1,1,6,60,8,0,75,10000,1
3,0,0,6,0,4,30,8,2,85,3000,1
4,0,0,6,0,4,30,8,2,85,3000,1

**Проверим на наличие пропусков в данных**

In [32]:
df.isna().sum()

Gender                     0
Age                        0
Occupation                 0
Sleep Duration             0
Quality of Sleep           0
Physical Activity Level    0
Stress Level               0
BMI Category               0
Heart Rate                 0
Daily Steps                0
PressureStatus             0
dtype: int64

### **Разобью данные на тренировочные и тестовые**

In [131]:
x_train, x_test, y_train, y_test = train_test_split(df, Y, random_state=100, test_size=0.3, stratify=Y)

## **Для полученных моделей с высоким качеством (2-3 модели) выполнить кросс-валидацию и сравнить результаты.**

### **Голосование большинством**

In [132]:
from sklearn.ensemble import VotingClassifier
from sklearn.compose import ColumnTransformer, make_column_selector

In [133]:
scale_features = ["Physical Activity Level", "Heart Rate", "Daily Steps", "Quality of Sleep", "Sleep Duration"]
preprocessor = ColumnTransformer([
    ('scaler', StandardScaler(), scale_features)
], remainder='passthrough')  # Оставляем остальные признаки без изменений'
pipeline1 = Pipeline([
    ('preprocessing', preprocessor),
    ('classifier', LogisticRegression(random_state=100, max_iter=1000))
])
pipeline2 = Pipeline([
    ('preprocessing', preprocessor),
    ('classifier', KNeighborsClassifier(n_neighbors=7)) 
])
pipeline3 = Pipeline([
    ('preprocessing', preprocessor),
    ('classifier', DecisionTreeClassifier(max_depth=6, random_state=42)) 
])
eclf = VotingClassifier(estimators=[('lr', pipeline1), ('knn', pipeline2), ('dt', pipeline3)], voting='hard')
eclf.fit(x_train, y_train)
train_predict = eclf.predict(x_train)
test_predict = eclf.predict(x_test)

In [134]:
print(f1_score(y_train, train_predict, average = 'macro'))
print(f1_score(y_test, test_predict, average = 'macro'))

0.9014482615551939
0.8523293270532185

In [135]:
from sklearn.model_selection import cross_val_score
model1 = VotingClassifier(estimators=[('lr', pipeline1), ('knn', pipeline2), ('dt', pipeline3)], voting='hard')
scores = cross_val_score(model1, x_train, y_train, cv=5, scoring='f1_macro')
print(scores)
print(scores.mean())

[0.81748191 0.84448653 0.8194855  0.93042494 0.89313747]
0.8610032705015385

### **Случайный лес**

In [136]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV

clf = RandomForestClassifier(random_state=100, n_estimators=7, max_features=6)
scores = cross_val_score(clf, x_train, y_train, cv=5, scoring='f1_macro')
print(scores)
print(scores.mean())

[0.80185645 0.84448653 0.83736406 0.93042494 0.86880607]
0.8565876103709039

In [137]:
clf.fit(x_train, y_train)
train_predict = clf.predict(x_train)
test_predict = clf.predict(x_test)

print(f1_score(y_train, train_predict, average='macro'))
print(f1_score(y_test, test_predict, average='macro'))

0.9229998841541572
0.9018005110203692

### **Бустинг**

In [138]:
from sklearn.ensemble import GradientBoostingClassifier

clf = GradientBoostingClassifier(n_estimators=25)

scores = cross_val_score(clf, x_train, y_train, cv=5, scoring='f1_macro')
print(scores)
print(scores.mean())

[0.82697947 0.82091982 0.88686869 0.93042494 0.88634838]
0.8703082607195316

In [139]:
clf.fit(x_train, y_train)
train_predict = clf.predict(x_train)
test_predict = clf.predict(x_test)
print(f1_score(y_train, train_predict, average='macro'))
print(f1_score(y_test, test_predict, average='macro'))

0.9229998841541572
0.89297829036635

**Наилучший средний f-score на фолдах у бустинга**

## Разбить исходную выборку на 3 подвыборки (обучающая, валидационная, тестовая). Для полученных моделей с высоким качеством (2-3 модели) определить наилучшие комбинации параметров, дающие лучшее значение по метрике F1 и сравнить результаты.

In [140]:
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.3, random_state=100, stratify=y_train)

In [141]:
pip install optuna

Requirement already satisfied: optuna in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (4.2.1)Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: alembic>=1.5.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from optuna) (1.15.1)
Requirement already satisfied: colorlog in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from optuna) (6.9.0)
Requirement already satisfied: numpy in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from optuna) (2.1.0)
Requirement already satisfied: packaging>=20.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from optuna) (24.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from optuna) (2.0.39)
Requirement already satisfied: tqdm in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from optuna) (4.67.0)
Requirement already satisfied: PyYAML in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from optuna) (6.0.2)
Requirement already satisfied: Mako in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from alembic>=1.5.0->optuna) (1.3.9)
Requirement already satisfied: typing-extensions>=4.12 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from alembic>=1.5.0->optuna) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy>=1.4.2->optuna) (3.1.1)
Requirement already satisfied: colorama in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from colorlog->optuna) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from Mako->alembic>=1.5.0->optuna) (2.1.5)

#### Голосование большинством

In [142]:
def objective_lr(trial):
    C = trial.suggest_loguniform('classifier__C', 0.01, 100)
    max_iter = trial.suggest_categorical('classifier__max_iter', [1000, 5000])
    pipeline1.set_params(classifier__C=C, classifier__max_iter=max_iter)
    return cross_val_score(pipeline1, x_train, y_train, cv=5, scoring='f1_macro').mean()

def objective_knn(trial):
    n_neighbors = trial.suggest_int('classifier__n_neighbors', 2, 10)
    pipeline2.set_params(classifier__n_neighbors=n_neighbors)
    return cross_val_score(pipeline2, x_train, y_train, cv=5, scoring='f1_macro').mean()

def objective_dt(trial):
    max_depth = trial.suggest_int('classifier__max_depth', 5, 9)
    pipeline3.set_params(classifier__max_depth=max_depth)
    return cross_val_score(pipeline3, x_train, y_train, cv=5, scoring='f1_macro').mean()

study_lr = optuna.create_study(direction='maximize')
study_lr.optimize(objective_lr, n_trials=20)

study_knn = optuna.create_study(direction='maximize')
study_knn.optimize(objective_knn, n_trials=20)

study_dt = optuna.create_study(direction='maximize')
study_dt.optimize(objective_dt, n_trials=20)

best_lr = pipeline1.set_params(**study_lr.best_params).fit(x_train, y_train)
best_knn = pipeline2.set_params(**study_knn.best_params).fit(x_train, y_train)
best_dt = pipeline3.set_params(**study_dt.best_params).fit(x_train, y_train)

eclf = VotingClassifier(estimators=[('lr', best_lr), ('knn', best_knn), ('dt', best_dt)], voting='hard')
eclf.fit(x_train, y_train)

val_predict = eclf.predict(x_val)
test_predict = eclf.predict(x_test)

print(f'F1 на валидационной {f1_score(y_val, val_predict, average="macro")}')
print(f'F1 на тестовой {f1_score(y_test, test_predict, average="macro")}')

[I 2025-03-16 16:38:49,594] A new study created in memory with name: no-name-33d9ee59-cb99-4f69-9d0f-8c6690ba0865
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1337643051.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:38:49,751] Trial 0 finished with value: 0.8893218991577404 and parameters: {'classifier__C': 3.789797915559348, 'classifier__max_iter': 1000}. Best is trial 0 with value: 0.8893218991577404.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1337643051.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:38:49,903] Trial 1 finished with value: 0.8953902752261165 and parameters: {'classifier__C': 7.427685693397078, 'classifier__max_iter': 5000}. Best is trial 1 with value: 0.8953902752261165.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1337643051.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:38:50,081] Trial 2 finished with value: 0.8772356629538571 and parameters: {'classifier__C': 39.36359473756997, 'classifier__max_iter': 5000}. Best is trial 1 with value: 0.8953902752261165.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1337643051.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:38:50,198] Trial 3 finished with value: 0.8121416008747173 and parameters: {'classifier__C': 0.019145544839499096, 'classifier__max_iter': 1000}. Best is trial 1 with value: 0.8953902752261165.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1337643051.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:38:50,264] Trial 4 finished with value: 0.8458292058472765 and parameters: {'classifier__C': 0.09700898656513574, 'classifier__max_iter': 1000}. Best is trial 1 with value: 0.8953902752261165.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1337643051.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:38:50,389] Trial 5 finished with value: 0.8893218991577404 and parameters: {'classifier__C': 1.4342261764993463, 'classifier__max_iter': 1000}. Best is trial 1 with value: 0.8953902752261165.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1337643051.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:38:50,480] Trial 6 finished with value: 0.827076011256894 and parameters: {'classifier__C': 0.07349952848594708, 'classifier__max_iter': 5000}. Best is trial 1 with value: 0.8953902752261165.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1337643051.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:38:50,596] Trial 7 finished with value: 0.8667551317732023 and parameters: {'classifier__C': 0.3819088634533003, 'classifier__max_iter': 1000}. Best is trial 1 with value: 0.8953902752261165.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1337643051.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:38:50,720] Trial 8 finished with value: 0.8893218991577404 and parameters: {'classifier__C': 3.140915304836205, 'classifier__max_iter': 1000}. Best is trial 1 with value: 0.8953902752261165.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1337643051.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:38:50,815] Trial 9 finished with value: 0.8159773935649992 and parameters: {'classifier__C': 0.030058918086895384, 'classifier__max_iter': 1000}. Best is trial 1 with value: 0.8953902752261165.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1337643051.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:38:51,005] Trial 10 finished with value: 0.8772356629538571 and parameters: {'classifier__C': 57.10800834419544, 'classifier__max_iter': 5000}. Best is trial 1 with value: 0.8953902752261165.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1337643051.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:38:51,165] Trial 11 finished with value: 0.8953902752261165 and parameters: {'classifier__C': 9.074914977534533, 'classifier__max_iter': 5000}. Best is trial 1 with value: 0.8953902752261165.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1337643051.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:38:51,309] Trial 12 finished with value: 0.8953902752261165 and parameters: {'classifier__C': 7.229339789735874, 'classifier__max_iter': 5000}. Best is trial 1 with value: 0.8953902752261165.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1337643051.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:38:51,459] Trial 13 finished with value: 0.8953902752261165 and parameters: {'classifier__C': 9.529636187781731, 'classifier__max_iter': 5000}. Best is trial 1 with value: 0.8953902752261165.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1337643051.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:38:51,625] Trial 14 finished with value: 0.8867594724776667 and parameters: {'classifier__C': 25.5293736469455, 'classifier__max_iter': 5000}. Best is trial 1 with value: 0.8953902752261165.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1337643051.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:38:51,698] Trial 15 finished with value: 0.8838089297423319 and parameters: {'classifier__C': 0.855765708574796, 'classifier__max_iter': 5000}. Best is trial 1 with value: 0.8953902752261165.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1337643051.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:38:51,920] Trial 16 finished with value: 0.8673479471837885 and parameters: {'classifier__C': 98.9434682291319, 'classifier__max_iter': 5000}. Best is trial 1 with value: 0.8953902752261165.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1337643051.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:38:52,082] Trial 17 finished with value: 0.8867594724776667 and parameters: {'classifier__C': 17.389614494586436, 'classifier__max_iter': 5000}. Best is trial 1 with value: 0.8953902752261165.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1337643051.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:38:52,192] Trial 18 finished with value: 0.8667551317732023 and parameters: {'classifier__C': 0.4156598747874809, 'classifier__max_iter': 5000}. Best is trial 1 with value: 0.8953902752261165.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1337643051.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:38:52,312] Trial 19 finished with value: 0.8893218991577404 and parameters: {'classifier__C': 3.004808633963325, 'classifier__max_iter': 5000}. Best is trial 1 with value: 0.8953902752261165.
[I 2025-03-16 16:38:52,313] A new study created in memory with name: no-name-18342910-d8cf-4459-8eb5-0f0be64e02e0
[I 2025-03-16 16:38:52,357] Trial 0 finished with value: 0.7919356358460212 and parameters: {'classifier__n_neighbors': 10}. Best is trial 0 with value: 0.7919356358460212.
[I 2025-03-16 16:38:52,415] Trial 1 finished with value: 0.8141029120585591 and parameters: {'classifier__n_neighbors': 6}. Best is trial 1 with value: 0.8141029120585591.
[I 2025-03-16 16:38:52,471] Trial 2 finished with value: 0.8076610449387467 and parameters: {'classifier__n_neighbors': 7}. Best is trial 1 with value: 0.8141029120585591.
[I 2025-03-16 16:38:52,528] Trial 3 finished with value: 0.8141029120585591 and parameters: {'classifier__n_neighbors': 6}. Best is trial 1 with value: 0.8141029120585591.
[I 2025-03-16 16:38:52,587] Trial 4 finished with value: 0.8106296804631427 and parameters: {'classifier__n_neighbors': 8}. Best is trial 1 with value: 0.8141029120585591.
[I 2025-03-16 16:38:52,637] Trial 5 finished with value: 0.8395251872878579 and parameters: {'classifier__n_neighbors': 2}. Best is trial 5 with value: 0.8395251872878579.
[I 2025-03-16 16:38:52,693] Trial 6 finished with value: 0.8395251872878579 and parameters: {'classifier__n_neighbors': 2}. Best is trial 5 with value: 0.8395251872878579.
[I 2025-03-16 16:38:52,752] Trial 7 finished with value: 0.8106296804631427 and parameters: {'classifier__n_neighbors': 8}. Best is trial 5 with value: 0.8395251872878579.
[I 2025-03-16 16:38:52,810] Trial 8 finished with value: 0.8106296804631427 and parameters: {'classifier__n_neighbors': 8}. Best is trial 5 with value: 0.8395251872878579.
[I 2025-03-16 16:38:52,870] Trial 9 finished with value: 0.8476010732713177 and parameters: {'classifier__n_neighbors': 3}. Best is trial 9 with value: 0.8476010732713177.
[I 2025-03-16 16:38:52,934] Trial 10 finished with value: 0.8419673638598679 and parameters: {'classifier__n_neighbors': 4}. Best is trial 9 with value: 0.8476010732713177.
[I 2025-03-16 16:38:53,001] Trial 11 finished with value: 0.8419673638598679 and parameters: {'classifier__n_neighbors': 4}. Best is trial 9 with value: 0.8476010732713177.
[I 2025-03-16 16:38:53,063] Trial 12 finished with value: 0.8419673638598679 and parameters: {'classifier__n_neighbors': 4}. Best is trial 9 with value: 0.8476010732713177.
[I 2025-03-16 16:38:53,128] Trial 13 finished with value: 0.8419673638598679 and parameters: {'classifier__n_neighbors': 4}. Best is trial 9 with value: 0.8476010732713177.
[I 2025-03-16 16:38:53,187] Trial 14 finished with value: 0.8476010732713177 and parameters: {'classifier__n_neighbors': 3}. Best is trial 9 with value: 0.8476010732713177.
[I 2025-03-16 16:38:53,254] Trial 15 finished with value: 0.8476010732713177 and parameters: {'classifier__n_neighbors': 3}. Best is trial 9 with value: 0.8476010732713177.
[I 2025-03-16 16:38:53,313] Trial 16 finished with value: 0.8291948510421898 and parameters: {'classifier__n_neighbors': 5}. Best is trial 9 with value: 0.8476010732713177.
[I 2025-03-16 16:38:53,380] Trial 17 finished with value: 0.8476010732713177 and parameters: {'classifier__n_neighbors': 3}. Best is trial 9 with value: 0.8476010732713177.
[I 2025-03-16 16:38:53,443] Trial 18 finished with value: 0.8395251872878579 and parameters: {'classifier__n_neighbors': 2}. Best is trial 9 with value: 0.8476010732713177.
[I 2025-03-16 16:38:53,508] Trial 19 finished with value: 0.8291948510421898 and parameters: {'classifier__n_neighbors': 5}. Best is trial 9 with value: 0.8476010732713177.
[I 2025-03-16 16:38:53,509] A new study created in memory with name: no-name-e24ff918-4581-4faa-adfa-64d140790c73
[I 2025-03-16 16:38:53,557] Trial 0 finished with value: 0.8173110700387213 and parameters: {'classifier__max_depth': 6}. Best is trial 0 with value: 0.8173110700387213.
[I 2025-03-16 16:38:53,611] Trial 1 finished with value: 0.8257726085002597 and parameters: {'classifier__max_depth': 7}. Best is trial 1 with value: 0.8257726085002597.
[I 2025-03-16 16:38:53,663] Trial 2 finished with value: 0.8343321861774845 and parameters: {'classifier__max_depth': 9}. Best is trial 2 with value: 0.8343321861774845.
[I 2025-03-16 16:38:53,713] Trial 3 finished with value: 0.8173110700387213 and parameters: {'classifier__max_depth': 6}. Best is trial 2 with value: 0.8343321861774845.
[I 2025-03-16 16:38:53,769] Trial 4 finished with value: 0.8257726085002597 and parameters: {'classifier__max_depth': 8}. Best is trial 2 with value: 0.8343321861774845.
[I 2025-03-16 16:38:53,830] Trial 5 finished with value: 0.8257726085002597 and parameters: {'classifier__max_depth': 8}. Best is trial 2 with value: 0.8343321861774845.
[I 2025-03-16 16:38:53,882] Trial 6 finished with value: 0.8257726085002597 and parameters: {'classifier__max_depth': 7}. Best is trial 2 with value: 0.8343321861774845.
[I 2025-03-16 16:38:53,929] Trial 7 finished with value: 0.8343321861774845 and parameters: {'classifier__max_depth': 9}. Best is trial 2 with value: 0.8343321861774845.
[I 2025-03-16 16:38:53,980] Trial 8 finished with value: 0.8240529070131164 and parameters: {'classifier__max_depth': 5}. Best is trial 2 with value: 0.8343321861774845.
[I 2025-03-16 16:38:54,030] Trial 9 finished with value: 0.8240529070131164 and parameters: {'classifier__max_depth': 5}. Best is trial 2 with value: 0.8343321861774845.
[I 2025-03-16 16:38:54,082] Trial 10 finished with value: 0.8343321861774845 and parameters: {'classifier__max_depth': 9}. Best is trial 2 with value: 0.8343321861774845.
[I 2025-03-16 16:38:54,139] Trial 11 finished with value: 0.8343321861774845 and parameters: {'classifier__max_depth': 9}. Best is trial 2 with value: 0.8343321861774845.
[I 2025-03-16 16:38:54,197] Trial 12 finished with value: 0.8343321861774845 and parameters: {'classifier__max_depth': 9}. Best is trial 2 with value: 0.8343321861774845.
[I 2025-03-16 16:38:54,256] Trial 13 finished with value: 0.8257726085002597 and parameters: {'classifier__max_depth': 8}. Best is trial 2 with value: 0.8343321861774845.
[I 2025-03-16 16:38:54,304] Trial 14 finished with value: 0.8343321861774845 and parameters: {'classifier__max_depth': 9}. Best is trial 2 with value: 0.8343321861774845.
[I 2025-03-16 16:38:54,354] Trial 15 finished with value: 0.8257726085002597 and parameters: {'classifier__max_depth': 8}. Best is trial 2 with value: 0.8343321861774845.
[I 2025-03-16 16:38:54,408] Trial 16 finished with value: 0.8343321861774845 and parameters: {'classifier__max_depth': 9}. Best is trial 2 with value: 0.8343321861774845.
[I 2025-03-16 16:38:54,438] Trial 17 finished with value: 0.8257726085002597 and parameters: {'classifier__max_depth': 8}. Best is trial 2 with value: 0.8343321861774845.
[I 2025-03-16 16:38:54,492] Trial 18 finished with value: 0.8257726085002597 and parameters: {'classifier__max_depth': 7}. Best is trial 2 with value: 0.8343321861774845.
[I 2025-03-16 16:38:54,549] Trial 19 finished with value: 0.8343321861774845 and parameters: {'classifier__max_depth': 9}. Best is trial 2 with value: 0.8343321861774845.

F1 на валидационной 0.8624542124542125
F1 на тестовой 0.860617039964866

#### Случайный лес

In [143]:
def objective(trial):
    n_estimators = trial.suggest_int('n_estimators', 1, 13)
    max_features = trial.suggest_int('max_features', 1, 10)
    
    clf = RandomForestClassifier(n_estimators=n_estimators, max_features=max_features, random_state=100)
    score = cross_val_score(clf, x_train, y_train, cv=5, scoring='f1_macro').mean()
    
    return score

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=20)

best_rf = RandomForestClassifier(**study.best_params, random_state=100)
best_rf.fit(x_train, y_train)

[I 2025-03-16 16:38:54,653] A new study created in memory with name: no-name-3a5018f7-4f70-4319-9c3c-3a3321985e6c
[I 2025-03-16 16:38:54,746] Trial 0 finished with value: 0.8389549688594601 and parameters: {'n_estimators': 11, 'max_features': 1}. Best is trial 0 with value: 0.8389549688594601.
[I 2025-03-16 16:38:54,791] Trial 1 finished with value: 0.8336205637126058 and parameters: {'n_estimators': 5, 'max_features': 10}. Best is trial 0 with value: 0.8389549688594601.
[I 2025-03-16 16:38:54,840] Trial 2 finished with value: 0.813820994675941 and parameters: {'n_estimators': 7, 'max_features': 5}. Best is trial 0 with value: 0.8389549688594601.
[I 2025-03-16 16:38:54,868] Trial 3 finished with value: 0.7995277779205374 and parameters: {'n_estimators': 1, 'max_features': 10}. Best is trial 0 with value: 0.8389549688594601.
[I 2025-03-16 16:38:54,911] Trial 4 finished with value: 0.8224974985972429 and parameters: {'n_estimators': 4, 'max_features': 6}. Best is trial 0 with value: 0.8389549688594601.
[I 2025-03-16 16:38:54,951] Trial 5 finished with value: 0.8268917033625511 and parameters: {'n_estimators': 3, 'max_features': 9}. Best is trial 0 with value: 0.8389549688594601.
[I 2025-03-16 16:38:54,993] Trial 6 finished with value: 0.8288867995746445 and parameters: {'n_estimators': 5, 'max_features': 1}. Best is trial 0 with value: 0.8389549688594601.
[I 2025-03-16 16:38:55,051] Trial 7 finished with value: 0.8227731536280999 and parameters: {'n_estimators': 8, 'max_features': 7}. Best is trial 0 with value: 0.8389549688594601.
[I 2025-03-16 16:38:55,124] Trial 8 finished with value: 0.8325378923994775 and parameters: {'n_estimators': 12, 'max_features': 5}. Best is trial 0 with value: 0.8389549688594601.
[I 2025-03-16 16:38:55,197] Trial 9 finished with value: 0.8326245224603637 and parameters: {'n_estimators': 10, 'max_features': 1}. Best is trial 0 with value: 0.8389549688594601.
[I 2025-03-16 16:38:55,265] Trial 10 finished with value: 0.8263301622125152 and parameters: {'n_estimators': 13, 'max_features': 3}. Best is trial 0 with value: 0.8389549688594601.
[I 2025-03-16 16:38:55,311] Trial 11 finished with value: 0.8143116151665615 and parameters: {'n_estimators': 8, 'max_features': 8}. Best is trial 0 with value: 0.8389549688594601.
[I 2025-03-16 16:38:55,380] Trial 12 finished with value: 0.8234076503899981 and parameters: {'n_estimators': 10, 'max_features': 4}. Best is trial 0 with value: 0.8389549688594601.
[I 2025-03-16 16:38:55,434] Trial 13 finished with value: 0.8311570588998769 and parameters: {'n_estimators': 5, 'max_features': 3}. Best is trial 0 with value: 0.8389549688594601.
[I 2025-03-16 16:38:55,516] Trial 14 finished with value: 0.8259439771123711 and parameters: {'n_estimators': 11, 'max_features': 10}. Best is trial 0 with value: 0.8389549688594601.
[I 2025-03-16 16:38:55,593] Trial 15 finished with value: 0.8288418136502482 and parameters: {'n_estimators': 7, 'max_features': 7}. Best is trial 0 with value: 0.8389549688594601.
[I 2025-03-16 16:38:55,638] Trial 16 finished with value: 0.8499132953989316 and parameters: {'n_estimators': 2, 'max_features': 2}. Best is trial 16 with value: 0.8499132953989316.
[I 2025-03-16 16:38:55,671] Trial 17 finished with value: 0.8279949497968113 and parameters: {'n_estimators': 1, 'max_features': 2}. Best is trial 16 with value: 0.8499132953989316.
[I 2025-03-16 16:38:55,712] Trial 18 finished with value: 0.8499132953989316 and parameters: {'n_estimators': 2, 'max_features': 2}. Best is trial 16 with value: 0.8499132953989316.
[I 2025-03-16 16:38:55,748] Trial 19 finished with value: 0.8363413740841923 and parameters: {'n_estimators': 2, 'max_features': 3}. Best is trial 16 with value: 0.8499132953989316.

RandomForestClassifier(max_features=2, n_estimators=2, random_state=100)

In [144]:
val_predict = best_rf.predict(x_val)
test_predict = best_rf.predict(x_test)

print(f'F1 на валидационной {f1_score(y_val, val_predict, average='macro')}')
print(f'F1 на тестовой {f1_score(y_test, test_predict, average='macro')}')

F1 на валидационной 0.826103779732812
F1 на тестовой 0.8477256153042033

#### Бустинг

In [145]:
def objective(trial):
    n_estimators = trial.suggest_categorical('n_estimators', [10, 20, 50, 100])
    learning_rate = trial.suggest_categorical('learning_rate', [0.01, 0.05, 0.1, 0.2])
    max_depth = trial.suggest_categorical('max_depth', [3, 5, 7, 10])
    
    clf = GradientBoostingClassifier(n_estimators=n_estimators, learning_rate=learning_rate, max_depth=max_depth)
    score = cross_val_score(clf, x_train, y_train, cv=5, scoring='f1_macro').mean()
    
    return score

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=20)

best_boost = GradientBoostingClassifier(**study.best_params)
best_boost.fit(x_train, y_train)

y_test_pred = best_boost.predict(x_test)
f1_test = f1_score(y_test, y_test_pred, average='macro')

[I 2025-03-16 16:38:55,771] A new study created in memory with name: no-name-ea372208-6424-4e97-9577-9b40f69b4aab
[I 2025-03-16 16:38:55,974] Trial 0 finished with value: 0.8255795176573741 and parameters: {'n_estimators': 10, 'learning_rate': 0.2, 'max_depth': 10}. Best is trial 0 with value: 0.8255795176573741.
[I 2025-03-16 16:38:56,347] Trial 1 finished with value: 0.8340410561189125 and parameters: {'n_estimators': 20, 'learning_rate': 0.05, 'max_depth': 7}. Best is trial 1 with value: 0.8340410561189125.
[I 2025-03-16 16:38:57,130] Trial 2 finished with value: 0.8405834026612592 and parameters: {'n_estimators': 50, 'learning_rate': 0.05, 'max_depth': 10}. Best is trial 2 with value: 0.8405834026612592.
[I 2025-03-16 16:38:58,021] Trial 3 finished with value: 0.8405834026612592 and parameters: {'n_estimators': 50, 'learning_rate': 0.05, 'max_depth': 10}. Best is trial 2 with value: 0.8405834026612592.
[I 2025-03-16 16:38:58,245] Trial 4 finished with value: 0.8324109905688853 and parameters: {'n_estimators': 10, 'learning_rate': 0.05, 'max_depth': 10}. Best is trial 2 with value: 0.8405834026612592.
[I 2025-03-16 16:38:58,425] Trial 5 finished with value: 0.8340410561189125 and parameters: {'n_estimators': 10, 'learning_rate': 0.2, 'max_depth': 10}. Best is trial 2 with value: 0.8405834026612592.
[I 2025-03-16 16:38:58,611] Trial 6 finished with value: 0.24680344930121914 and parameters: {'n_estimators': 10, 'learning_rate': 0.01, 'max_depth': 5}. Best is trial 2 with value: 0.8405834026612592.
[I 2025-03-16 16:38:59,136] Trial 7 finished with value: 0.8361233270240399 and parameters: {'n_estimators': 50, 'learning_rate': 0.2, 'max_depth': 3}. Best is trial 2 with value: 0.8405834026612592.
[I 2025-03-16 16:38:59,251] Trial 8 finished with value: 0.24680344930121914 and parameters: {'n_estimators': 10, 'learning_rate': 0.01, 'max_depth': 3}. Best is trial 2 with value: 0.8405834026612592.
[I 2025-03-16 16:38:59,435] Trial 9 finished with value: 0.8304871005054604 and parameters: {'n_estimators': 10, 'learning_rate': 0.05, 'max_depth': 5}. Best is trial 2 with value: 0.8405834026612592.
[I 2025-03-16 16:39:01,360] Trial 10 finished with value: 0.8295856786259265 and parameters: {'n_estimators': 100, 'learning_rate': 0.1, 'max_depth': 7}. Best is trial 2 with value: 0.8405834026612592.
[I 2025-03-16 16:39:02,285] Trial 11 finished with value: 0.8405834026612592 and parameters: {'n_estimators': 50, 'learning_rate': 0.05, 'max_depth': 10}. Best is trial 2 with value: 0.8405834026612592.
[I 2025-03-16 16:39:03,145] Trial 12 finished with value: 0.8405834026612592 and parameters: {'n_estimators': 50, 'learning_rate': 0.05, 'max_depth': 10}. Best is trial 2 with value: 0.8405834026612592.
[I 2025-03-16 16:39:03,951] Trial 13 finished with value: 0.823562286522496 and parameters: {'n_estimators': 50, 'learning_rate': 0.1, 'max_depth': 10}. Best is trial 2 with value: 0.8405834026612592.
[I 2025-03-16 16:39:04,673] Trial 14 finished with value: 0.8321218641997208 and parameters: {'n_estimators': 50, 'learning_rate': 0.05, 'max_depth': 10}. Best is trial 2 with value: 0.8405834026612592.
[I 2025-03-16 16:39:05,091] Trial 15 finished with value: 0.8340410561189125 and parameters: {'n_estimators': 20, 'learning_rate': 0.05, 'max_depth': 10}. Best is trial 2 with value: 0.8405834026612592.
[I 2025-03-16 16:39:06,081] Trial 16 finished with value: 0.8276617885625015 and parameters: {'n_estimators': 100, 'learning_rate': 0.05, 'max_depth': 3}. Best is trial 2 with value: 0.8405834026612592.
[I 2025-03-16 16:39:06,868] Trial 17 finished with value: 0.8324109905688853 and parameters: {'n_estimators': 50, 'learning_rate': 0.01, 'max_depth': 7}. Best is trial 2 with value: 0.8405834026612592.
[I 2025-03-16 16:39:07,603] Trial 18 finished with value: 0.823562286522496 and parameters: {'n_estimators': 50, 'learning_rate': 0.1, 'max_depth': 5}. Best is trial 2 with value: 0.8405834026612592.
[I 2025-03-16 16:39:08,461] Trial 19 finished with value: 0.8405834026612592 and parameters: {'n_estimators': 50, 'learning_rate': 0.05, 'max_depth': 10}. Best is trial 2 with value: 0.8405834026612592.

In [146]:
val_predict = best_boost.predict(x_val)
test_predict = best_boost.predict(x_test)

print(f'F1 на валидационной {f1_score(y_val, val_predict, average='macro')}')
print(f'F1 на тестовой {f1_score(y_test, test_predict, average='macro')}')

F1 на валидационной 0.8557118499573743
F1 на тестовой 0.8763078353871192

### Подготовить и обучить итоговую модель (ансамбль) с применением различных техник. Выполнить сравнительный анализ полученных результатов.

In [83]:
x_train = pd.concat([x_train, x_val], axis=0)
y_train = pd.concat([y_train, y_val], axis=0)

In [91]:
from sklearn.ensemble import StackingClassifier

In [101]:
def objective_lr(trial):
    C = trial.suggest_loguniform('classifier__C', 0.01, 100)
    max_iter = trial.suggest_categorical('classifier__max_iter', [1000, 5000])
    pipeline1.set_params(classifier__C=C, classifier__max_iter=max_iter)
    return cross_val_score(pipeline1, x_train, y_train, cv=5, scoring='f1_macro').mean()

study_lr = optuna.create_study(direction='maximize')
study_lr.optimize(objective_lr, n_trials=20)
best_lr = pipeline1.set_params(**study_lr.best_params).fit(x_train, y_train)

# Оптимизация гиперпараметров для KNN
def objective_knn(trial):
    n_neighbors = trial.suggest_int('classifier__n_neighbors', 2, 10)
    pipeline2.set_params(classifier__n_neighbors=n_neighbors)
    return cross_val_score(pipeline2, x_train, y_train, cv=5, scoring='f1_macro').mean()

study_knn = optuna.create_study(direction='maximize')
study_knn.optimize(objective_knn, n_trials=20)
best_knn = pipeline2.set_params(**study_knn.best_params).fit(x_train, y_train)

# Оптимизация гиперпараметров для дерева решений
def objective_dt(trial):
    max_depth = trial.suggest_int('classifier__max_depth', 5, 9)
    pipeline3.set_params(classifier__max_depth=max_depth)
    return cross_val_score(pipeline3, x_train, y_train, cv=5, scoring='f1_macro').mean()

study_dt = optuna.create_study(direction='maximize')
study_dt.optimize(objective_dt, n_trials=20)
best_dt = pipeline3.set_params(**study_dt.best_params).fit(x_train, y_train)

# Создание вотинг-классификатора
voting_clf = VotingClassifier(estimators=[
    ('lr', best_lr),
    ('knn', best_knn),
    ('dt', best_dt)
], voting='hard')

# Обучение случайного леса
def objective_rf(trial):
    n_estimators = trial.suggest_int('n_estimators', 1, 13)
    max_features = trial.suggest_int('max_features', 1, 10)
    
    clf = RandomForestClassifier(n_estimators=n_estimators, max_features=max_features, random_state=100)
    return cross_val_score(clf, x_train, y_train, cv=5, scoring='f1_macro').mean()

study_rf = optuna.create_study(direction='maximize')
study_rf.optimize(objective_rf, n_trials=20)
best_rf = RandomForestClassifier(**study_rf.best_params, random_state=100).fit(x_train, y_train)

# Оптимизация градиентного бустинга
def objective_boost(trial):
    n_estimators = trial.suggest_categorical('n_estimators', [10, 20, 50, 100])
    learning_rate = trial.suggest_categorical('learning_rate', [0.01, 0.05, 0.1, 0.2])
    max_depth = trial.suggest_categorical('max_depth', [3, 5, 7, 10])
    
    clf = GradientBoostingClassifier(n_estimators=n_estimators, learning_rate=learning_rate, max_depth=max_depth)
    return cross_val_score(clf, x_train, y_train, cv=5, scoring='f1_macro').mean()

study_boost = optuna.create_study(direction='maximize')
study_boost.optimize(objective_boost, n_trials=20)
best_boost = GradientBoostingClassifier(**study_boost.best_params).fit(x_train, y_train)

# Создание стекинг-классификатора, где вотинг-классификатор, случайный лес и градиентный бустинг - базовые модели
stacking_clf = StackingClassifier(estimators=[
    ('voting', voting_clf),
    ('rf', best_rf),
    ('boost', best_boost)
], final_estimator=LogisticRegression())

# Обучение стекинга
stacking_clf.fit(x_train, y_train)

[I 2025-03-16 16:27:04,992] A new study created in memory with name: no-name-4b261dc7-4d4d-420c-b5b9-03b7563013a4
C:\Users\User\AppData\Local\Temp\ipykernel_21536\2126275131.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:27:05,034] Trial 0 finished with value: 0.8599006651147354 and parameters: {'classifier__C': 0.05068848054751701, 'classifier__max_iter': 1000}. Best is trial 0 with value: 0.8599006651147354.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\2126275131.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:27:05,123] Trial 1 finished with value: 0.8739177095075361 and parameters: {'classifier__C': 34.7683336314779, 'classifier__max_iter': 1000}. Best is trial 1 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\2126275131.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:27:05,175] Trial 2 finished with value: 0.8739177095075361 and parameters: {'classifier__C': 5.748862855166972, 'classifier__max_iter': 1000}. Best is trial 1 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\2126275131.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:27:05,209] Trial 3 finished with value: 0.8725099144435529 and parameters: {'classifier__C': 0.3885864852614041, 'classifier__max_iter': 1000}. Best is trial 1 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\2126275131.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:27:05,243] Trial 4 finished with value: 0.8645722360776018 and parameters: {'classifier__C': 0.8455638859406684, 'classifier__max_iter': 1000}. Best is trial 1 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\2126275131.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:27:05,289] Trial 5 finished with value: 0.8660319465066836 and parameters: {'classifier__C': 36.80014859262596, 'classifier__max_iter': 1000}. Best is trial 1 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\2126275131.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:27:05,323] Trial 6 finished with value: 0.8736198736219368 and parameters: {'classifier__C': 0.08438342265438915, 'classifier__max_iter': 1000}. Best is trial 1 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\2126275131.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:27:05,369] Trial 7 finished with value: 0.8739177095075361 and parameters: {'classifier__C': 25.372533418518735, 'classifier__max_iter': 5000}. Best is trial 1 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\2126275131.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:27:05,403] Trial 8 finished with value: 0.8736198736219368 and parameters: {'classifier__C': 0.07400330873267204, 'classifier__max_iter': 5000}. Best is trial 1 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\2126275131.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:27:05,480] Trial 9 finished with value: 0.8660319465066836 and parameters: {'classifier__C': 50.273163662030996, 'classifier__max_iter': 1000}. Best is trial 1 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\2126275131.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:27:05,543] Trial 10 finished with value: 0.8739177095075361 and parameters: {'classifier__C': 5.58240506499686, 'classifier__max_iter': 5000}. Best is trial 1 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\2126275131.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:27:05,588] Trial 11 finished with value: 0.8739177095075361 and parameters: {'classifier__C': 5.869637196163455, 'classifier__max_iter': 1000}. Best is trial 1 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\2126275131.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:27:05,636] Trial 12 finished with value: 0.8739177095075361 and parameters: {'classifier__C': 6.514607080141422, 'classifier__max_iter': 1000}. Best is trial 1 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\2126275131.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:27:05,699] Trial 13 finished with value: 0.8660319465066836 and parameters: {'classifier__C': 90.69378751508707, 'classifier__max_iter': 1000}. Best is trial 1 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\2126275131.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:27:05,764] Trial 14 finished with value: 0.8739177095075361 and parameters: {'classifier__C': 12.469090216912841, 'classifier__max_iter': 5000}. Best is trial 1 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\2126275131.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:27:05,810] Trial 15 finished with value: 0.8700734727001199 and parameters: {'classifier__C': 1.4303425231445535, 'classifier__max_iter': 1000}. Best is trial 1 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\2126275131.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:27:05,847] Trial 16 finished with value: 0.8333947024173598 and parameters: {'classifier__C': 0.014535220265343955, 'classifier__max_iter': 1000}. Best is trial 1 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\2126275131.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:27:05,888] Trial 17 finished with value: 0.8700734727001199 and parameters: {'classifier__C': 2.5665327958025714, 'classifier__max_iter': 1000}. Best is trial 1 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\2126275131.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:27:05,937] Trial 18 finished with value: 0.8739177095075361 and parameters: {'classifier__C': 15.558434743013597, 'classifier__max_iter': 5000}. Best is trial 1 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\2126275131.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:27:05,974] Trial 19 finished with value: 0.8680643180663813 and parameters: {'classifier__C': 0.333290944106265, 'classifier__max_iter': 1000}. Best is trial 1 with value: 0.8739177095075361.
[I 2025-03-16 16:27:05,982] A new study created in memory with name: no-name-44ca21f3-0d9c-41b2-b4cf-d7b668b14e08
[I 2025-03-16 16:27:06,023] Trial 0 finished with value: 0.853757337534556 and parameters: {'classifier__n_neighbors': 5}. Best is trial 0 with value: 0.853757337534556.
[I 2025-03-16 16:27:06,057] Trial 1 finished with value: 0.8540614497948409 and parameters: {'classifier__n_neighbors': 7}. Best is trial 1 with value: 0.8540614497948409.
[I 2025-03-16 16:27:06,092] Trial 2 finished with value: 0.7782152622399959 and parameters: {'classifier__n_neighbors': 2}. Best is trial 1 with value: 0.8540614497948409.
[I 2025-03-16 16:27:06,124] Trial 3 finished with value: 0.853757337534556 and parameters: {'classifier__n_neighbors': 5}. Best is trial 1 with value: 0.8540614497948409.
[I 2025-03-16 16:27:06,167] Trial 4 finished with value: 0.8708393323014378 and parameters: {'classifier__n_neighbors': 4}. Best is trial 4 with value: 0.8708393323014378.
[I 2025-03-16 16:27:06,208] Trial 5 finished with value: 0.8540614497948409 and parameters: {'classifier__n_neighbors': 8}. Best is trial 4 with value: 0.8708393323014378.
[I 2025-03-16 16:27:06,244] Trial 6 finished with value: 0.851061726419356 and parameters: {'classifier__n_neighbors': 10}. Best is trial 4 with value: 0.8708393323014378.
[I 2025-03-16 16:27:06,274] Trial 7 finished with value: 0.853757337534556 and parameters: {'classifier__n_neighbors': 5}. Best is trial 4 with value: 0.8708393323014378.
[I 2025-03-16 16:27:06,300] Trial 8 finished with value: 0.8540614497948409 and parameters: {'classifier__n_neighbors': 7}. Best is trial 4 with value: 0.8708393323014378.
[I 2025-03-16 16:27:06,332] Trial 9 finished with value: 0.8500025078601375 and parameters: {'classifier__n_neighbors': 9}. Best is trial 4 with value: 0.8708393323014378.
[I 2025-03-16 16:27:06,379] Trial 10 finished with value: 0.7782152622399959 and parameters: {'classifier__n_neighbors': 2}. Best is trial 4 with value: 0.8708393323014378.
[I 2025-03-16 16:27:06,420] Trial 11 finished with value: 0.8708393323014378 and parameters: {'classifier__n_neighbors': 4}. Best is trial 4 with value: 0.8708393323014378.
[I 2025-03-16 16:27:06,471] Trial 12 finished with value: 0.852472535627216 and parameters: {'classifier__n_neighbors': 3}. Best is trial 4 with value: 0.8708393323014378.
[I 2025-03-16 16:27:06,522] Trial 13 finished with value: 0.8708393323014378 and parameters: {'classifier__n_neighbors': 4}. Best is trial 4 with value: 0.8708393323014378.
[I 2025-03-16 16:27:06,560] Trial 14 finished with value: 0.8708393323014378 and parameters: {'classifier__n_neighbors': 4}. Best is trial 4 with value: 0.8708393323014378.
[I 2025-03-16 16:27:06,598] Trial 15 finished with value: 0.852472535627216 and parameters: {'classifier__n_neighbors': 3}. Best is trial 4 with value: 0.8708393323014378.
[I 2025-03-16 16:27:06,636] Trial 16 finished with value: 0.8644490499806544 and parameters: {'classifier__n_neighbors': 6}. Best is trial 4 with value: 0.8708393323014378.
[I 2025-03-16 16:27:06,675] Trial 17 finished with value: 0.8708393323014378 and parameters: {'classifier__n_neighbors': 4}. Best is trial 4 with value: 0.8708393323014378.
[I 2025-03-16 16:27:06,717] Trial 18 finished with value: 0.8644490499806544 and parameters: {'classifier__n_neighbors': 6}. Best is trial 4 with value: 0.8708393323014378.
[I 2025-03-16 16:27:06,754] Trial 19 finished with value: 0.852472535627216 and parameters: {'classifier__n_neighbors': 3}. Best is trial 4 with value: 0.8708393323014378.
[I 2025-03-16 16:27:06,757] A new study created in memory with name: no-name-93f6926f-8114-4fb2-92ae-816ea7e901e8
[I 2025-03-16 16:27:06,783] Trial 0 finished with value: 0.8602455368427602 and parameters: {'classifier__max_depth': 6}. Best is trial 0 with value: 0.8602455368427602.
[I 2025-03-16 16:27:06,815] Trial 1 finished with value: 0.8633774884679906 and parameters: {'classifier__max_depth': 9}. Best is trial 1 with value: 0.8633774884679906.
[I 2025-03-16 16:27:06,842] Trial 2 finished with value: 0.8574988260675891 and parameters: {'classifier__max_depth': 9}. Best is trial 1 with value: 0.8633774884679906.
[I 2025-03-16 16:27:06,873] Trial 3 finished with value: 0.8711035433168076 and parameters: {'classifier__max_depth': 5}. Best is trial 3 with value: 0.8711035433168076.
[I 2025-03-16 16:27:06,899] Trial 4 finished with value: 0.8679715916915771 and parameters: {'classifier__max_depth': 5}. Best is trial 3 with value: 0.8711035433168076.
[I 2025-03-16 16:27:06,921] Trial 5 finished with value: 0.8574988260675891 and parameters: {'classifier__max_depth': 8}. Best is trial 3 with value: 0.8711035433168076.
[I 2025-03-16 16:27:06,942] Trial 6 finished with value: 0.8682946985364233 and parameters: {'classifier__max_depth': 7}. Best is trial 3 with value: 0.8711035433168076.
[I 2025-03-16 16:27:06,966] Trial 7 finished with value: 0.8602455368427602 and parameters: {'classifier__max_depth': 6}. Best is trial 3 with value: 0.8711035433168076.
[I 2025-03-16 16:27:06,992] Trial 8 finished with value: 0.8581996725356991 and parameters: {'classifier__max_depth': 5}. Best is trial 3 with value: 0.8711035433168076.
[I 2025-03-16 16:27:07,017] Trial 9 finished with value: 0.8655479877612521 and parameters: {'classifier__max_depth': 5}. Best is trial 3 with value: 0.8711035433168076.
[I 2025-03-16 16:27:07,043] Trial 10 finished with value: 0.8691745899172659 and parameters: {'classifier__max_depth': 7}. Best is trial 3 with value: 0.8711035433168076.
[I 2025-03-16 16:27:07,069] Trial 11 finished with value: 0.8630554272763643 and parameters: {'classifier__max_depth': 7}. Best is trial 3 with value: 0.8711035433168076.
[I 2025-03-16 16:27:07,100] Trial 12 finished with value: 0.8562111169026421 and parameters: {'classifier__max_depth': 6}. Best is trial 3 with value: 0.8711035433168076.
[I 2025-03-16 16:27:07,134] Trial 13 finished with value: 0.8630554272763643 and parameters: {'classifier__max_depth': 8}. Best is trial 3 with value: 0.8711035433168076.
[I 2025-03-16 16:27:07,158] Trial 14 finished with value: 0.8602455368427602 and parameters: {'classifier__max_depth': 8}. Best is trial 3 with value: 0.8711035433168076.
[I 2025-03-16 16:27:07,189] Trial 15 finished with value: 0.8562111169026421 and parameters: {'classifier__max_depth': 6}. Best is trial 3 with value: 0.8711035433168076.
[I 2025-03-16 16:27:07,220] Trial 16 finished with value: 0.8530791652774117 and parameters: {'classifier__max_depth': 7}. Best is trial 3 with value: 0.8711035433168076.
[I 2025-03-16 16:27:07,252] Trial 17 finished with value: 0.8599234756511338 and parameters: {'classifier__max_depth': 7}. Best is trial 3 with value: 0.8711035433168076.
[I 2025-03-16 16:27:07,284] Trial 18 finished with value: 0.8552496645706732 and parameters: {'classifier__max_depth': 5}. Best is trial 3 with value: 0.8711035433168076.
[I 2025-03-16 16:27:07,322] Trial 19 finished with value: 0.8472005028770102 and parameters: {'classifier__max_depth': 8}. Best is trial 3 with value: 0.8711035433168076.
[I 2025-03-16 16:27:07,325] A new study created in memory with name: no-name-ad00e989-cbf6-4ca2-a65f-5a976bd5d72f
[I 2025-03-16 16:27:07,378] Trial 0 finished with value: 0.8541383838366302 and parameters: {'n_estimators': 5, 'max_features': 9}. Best is trial 0 with value: 0.8541383838366302.
[I 2025-03-16 16:27:07,463] Trial 1 finished with value: 0.8562762470089862 and parameters: {'n_estimators': 13, 'max_features': 5}. Best is trial 1 with value: 0.8562762470089862.
[I 2025-03-16 16:27:07,515] Trial 2 finished with value: 0.8519176665249955 and parameters: {'n_estimators': 5, 'max_features': 1}. Best is trial 1 with value: 0.8562762470089862.
[I 2025-03-16 16:27:07,569] Trial 3 finished with value: 0.849620566437457 and parameters: {'n_estimators': 5, 'max_features': 10}. Best is trial 1 with value: 0.8562762470089862.
[I 2025-03-16 16:27:07,604] Trial 4 finished with value: 0.8424702083957902 and parameters: {'n_estimators': 2, 'max_features': 10}. Best is trial 1 with value: 0.8562762470089862.
[I 2025-03-16 16:27:07,639] Trial 5 finished with value: 0.8660923409056196 and parameters: {'n_estimators': 2, 'max_features': 4}. Best is trial 5 with value: 0.8660923409056196.
[I 2025-03-16 16:27:07,714] Trial 6 finished with value: 0.8572556998870361 and parameters: {'n_estimators': 12, 'max_features': 1}. Best is trial 5 with value: 0.8660923409056196.
[I 2025-03-16 16:27:07,792] Trial 7 finished with value: 0.8575340085349099 and parameters: {'n_estimators': 9, 'max_features': 1}. Best is trial 5 with value: 0.8660923409056196.
[I 2025-03-16 16:27:07,843] Trial 8 finished with value: 0.8643517345608809 and parameters: {'n_estimators': 4, 'max_features': 6}. Best is trial 5 with value: 0.8660923409056196.
[I 2025-03-16 16:27:07,903] Trial 9 finished with value: 0.8575340085349099 and parameters: {'n_estimators': 9, 'max_features': 1}. Best is trial 5 with value: 0.8660923409056196.

StackingClassifier(estimators=[('voting',
                                VotingClassifier(estimators=[('lr',
                                                              Pipeline(steps=[('scaler',
                                                                               StandardScaler()),
                                                                              ('classifier',
                                                                               LogisticRegression(C=34.7683336314779,
                                                                                                  max_iter=1000))])),
                                                             ('knn',
                                                              Pipeline(steps=[('scaler',
                                                                               StandardScaler()),
                                                                              ('classifier',
                                                                               KNeighborsClassifier(n_neighbors=4))])),
                                                             ('dt',
                                                              Pipeline(steps=[('scaler',
                                                                               StandardScaler()),
                                                                              ('classifier',
                                                                               DecisionTreeClassifier(max_depth=5))]))])),
                               ('rf',
                                RandomForestClassifier(max_features=4,
                                                       n_estimators=2,
                                                       random_state=100)),
                               ('boost',
                                GradientBoostingClassifier(n_estimators=20))],
                   final_estimator=LogisticRegression())

In [102]:
train_predict = stacking_clf.predict(x_train)
test_predict = stacking_clf.predict(x_test)

print("F1-score (train):", f1_score(y_train, train_predict, average='macro'))
print("F1-score (test):", f1_score(y_test, test_predict, average='macro'))

F1-score (train): 0.9168423988342181
F1-score (test): 0.8724645987057335

In [99]:
def objective_lr(trial):
    C = trial.suggest_loguniform('classifier__C', 0.01, 100)
    max_iter = trial.suggest_categorical('classifier__max_iter', [1000, 5000])
    pipeline1.set_params(classifier__C=C, classifier__max_iter=max_iter)
    return cross_val_score(pipeline1, x_train, y_train, cv=5, scoring='f1_macro').mean()

# Для второй модели (KNN)
def objective_knn(trial):
    n_neighbors = trial.suggest_int('classifier__n_neighbors', 2, 10)
    pipeline2.set_params(classifier__n_neighbors=n_neighbors)
    return cross_val_score(pipeline2, x_train, y_train, cv=5, scoring='f1_macro').mean()

# Для третьей модели (дерево решений)
def objective_dt(trial):
    max_depth = trial.suggest_int('classifier__max_depth', 5, 9)
    pipeline3.set_params(classifier__max_depth=max_depth)
    return cross_val_score(pipeline3, x_train, y_train, cv=5, scoring='f1_macro').mean()

# Оптимизация гиперпараметров для каждой модели
study_lr = optuna.create_study(direction='maximize')
study_lr.optimize(objective_lr, n_trials=20)

study_knn = optuna.create_study(direction='maximize')
study_knn.optimize(objective_knn, n_trials=20)

study_dt = optuna.create_study(direction='maximize')
study_dt.optimize(objective_dt, n_trials=20)

# Обучение моделей с лучшими параметрами
best_lr = pipeline1.set_params(**study_lr.best_params).fit(x_train, y_train)
best_knn = pipeline2.set_params(**study_knn.best_params).fit(x_train, y_train)
best_dt = pipeline3.set_params(**study_dt.best_params).fit(x_train, y_train)

# Обучение случайного леса
def objective_rf(trial):
    n_estimators = trial.suggest_int('n_estimators', 1, 13)
    max_features = trial.suggest_int('max_features', 1, 10)
    
    clf = RandomForestClassifier(n_estimators=n_estimators, max_features=max_features, random_state=100)
    score = cross_val_score(clf, x_train, y_train, cv=5, scoring='f1_macro').mean()
    
    return score

study_rf = optuna.create_study(direction='maximize')
study_rf.optimize(objective_rf, n_trials=20)

best_rf = RandomForestClassifier(**study_rf.best_params, random_state=100).fit(x_train, y_train)

# Обучение модели градиентного бустинга
def objective_boost(trial):
    n_estimators = trial.suggest_categorical('n_estimators', [10, 20, 50, 100])
    learning_rate = trial.suggest_categorical('learning_rate', [0.01, 0.05, 0.1, 0.2])
    max_depth = trial.suggest_categorical('max_depth', [3, 5, 7, 10])
    
    clf = GradientBoostingClassifier(n_estimators=n_estimators, learning_rate=learning_rate, max_depth=max_depth)
    score = cross_val_score(clf, x_train, y_train, cv=5, scoring='f1_macro').mean()
    
    return score

study_boost = optuna.create_study(direction='maximize')
study_boost.optimize(objective_boost, n_trials=20)

best_boost = GradientBoostingClassifier(**study_boost.best_params).fit(x_train, y_train)

# Создание стекинг-ассембля с тремя базовыми моделями
estimators = [
    ('lr', best_lr),
    ('knn', best_knn),
    ('dt', best_dt),
    ('rf', best_rf),
    ('boost', best_boost)
]

stacking_clf = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())

# Обучение стекинг-ассембля
stacking_clf.fit(x_train, y_train)

[I 2025-03-16 16:22:27,461] A new study created in memory with name: no-name-29a842ac-ce7b-417e-81a5-c1dc524e1eb9
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1743787916.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:22:27,506] Trial 0 finished with value: 0.8739177095075361 and parameters: {'classifier__C': 5.551792776536298, 'classifier__max_iter': 1000}. Best is trial 0 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1743787916.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:22:27,564] Trial 1 finished with value: 0.8333947024173598 and parameters: {'classifier__C': 0.014589107296403015, 'classifier__max_iter': 1000}. Best is trial 0 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1743787916.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:22:27,619] Trial 2 finished with value: 0.8660319465066836 and parameters: {'classifier__C': 59.861556106744246, 'classifier__max_iter': 5000}. Best is trial 0 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1743787916.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:22:27,659] Trial 3 finished with value: 0.8303074787480884 and parameters: {'classifier__C': 0.018302031840035617, 'classifier__max_iter': 1000}. Best is trial 0 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1743787916.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:22:27,710] Trial 4 finished with value: 0.8660319465066836 and parameters: {'classifier__C': 89.44647254390401, 'classifier__max_iter': 5000}. Best is trial 0 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1743787916.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:22:27,750] Trial 5 finished with value: 0.8739177095075361 and parameters: {'classifier__C': 11.142630852676266, 'classifier__max_iter': 5000}. Best is trial 0 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1743787916.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:22:27,786] Trial 6 finished with value: 0.8700734727001199 and parameters: {'classifier__C': 2.2424611955922384, 'classifier__max_iter': 1000}. Best is trial 0 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1743787916.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:22:27,823] Trial 7 finished with value: 0.8700734727001199 and parameters: {'classifier__C': 1.698693772898516, 'classifier__max_iter': 1000}. Best is trial 0 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1743787916.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:22:27,870] Trial 8 finished with value: 0.8660319465066836 and parameters: {'classifier__C': 55.429350261846466, 'classifier__max_iter': 5000}. Best is trial 0 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1743787916.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:22:27,901] Trial 9 finished with value: 0.834800476891559 and parameters: {'classifier__C': 0.03560905952499468, 'classifier__max_iter': 5000}. Best is trial 0 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1743787916.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:22:27,937] Trial 10 finished with value: 0.8680643180663813 and parameters: {'classifier__C': 0.14560286631190172, 'classifier__max_iter': 1000}. Best is trial 0 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1743787916.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:22:27,981] Trial 11 finished with value: 0.8739177095075361 and parameters: {'classifier__C': 8.210224405432903, 'classifier__max_iter': 5000}. Best is trial 0 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1743787916.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:22:28,023] Trial 12 finished with value: 0.8739177095075361 and parameters: {'classifier__C': 10.226562121771018, 'classifier__max_iter': 1000}. Best is trial 0 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1743787916.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:22:28,065] Trial 13 finished with value: 0.8739177095075361 and parameters: {'classifier__C': 10.473352047634043, 'classifier__max_iter': 5000}. Best is trial 0 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1743787916.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:22:28,102] Trial 14 finished with value: 0.8680643180663813 and parameters: {'classifier__C': 0.31573026191863335, 'classifier__max_iter': 1000}. Best is trial 0 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1743787916.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:22:28,147] Trial 15 finished with value: 0.8739177095075361 and parameters: {'classifier__C': 3.5148474223184065, 'classifier__max_iter': 5000}. Best is trial 0 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1743787916.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:22:28,187] Trial 16 finished with value: 0.8690463945326645 and parameters: {'classifier__C': 0.6728045993155557, 'classifier__max_iter': 5000}. Best is trial 0 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1743787916.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:22:28,272] Trial 17 finished with value: 0.8739177095075361 and parameters: {'classifier__C': 15.722346311068103, 'classifier__max_iter': 1000}. Best is trial 0 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1743787916.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:22:28,329] Trial 18 finished with value: 0.8739177095075361 and parameters: {'classifier__C': 4.092843037372428, 'classifier__max_iter': 5000}. Best is trial 0 with value: 0.8739177095075361.
C:\Users\User\AppData\Local\Temp\ipykernel_21536\1743787916.py:2: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  C = trial.suggest_loguniform('classifier__C', 0.01, 100)
[I 2025-03-16 16:22:28,380] Trial 19 finished with value: 0.8739177095075361 and parameters: {'classifier__C': 25.31252788068457, 'classifier__max_iter': 1000}. Best is trial 0 with value: 0.8739177095075361.
[I 2025-03-16 16:22:28,381] A new study created in memory with name: no-name-3905c1ce-faa1-457c-8b02-97662e8315df
[I 2025-03-16 16:22:28,415] Trial 0 finished with value: 0.7782152622399959 and parameters: {'classifier__n_neighbors': 2}. Best is trial 0 with value: 0.7782152622399959.
[I 2025-03-16 16:22:28,454] Trial 1 finished with value: 0.7782152622399959 and parameters: {'classifier__n_neighbors': 2}. Best is trial 0 with value: 0.7782152622399959.
[I 2025-03-16 16:22:28,491] Trial 2 finished with value: 0.8540614497948409 and parameters: {'classifier__n_neighbors': 8}. Best is trial 2 with value: 0.8540614497948409.
[I 2025-03-16 16:22:28,525] Trial 3 finished with value: 0.8708393323014378 and parameters: {'classifier__n_neighbors': 4}. Best is trial 3 with value: 0.8708393323014378.
[I 2025-03-16 16:22:28,558] Trial 4 finished with value: 0.8708393323014378 and parameters: {'classifier__n_neighbors': 4}. Best is trial 3 with value: 0.8708393323014378.
[I 2025-03-16 16:22:28,766] Trial 5 finished with value: 0.8540614497948409 and parameters: {'classifier__n_neighbors': 8}. Best is trial 3 with value: 0.8708393323014378.
[I 2025-03-16 16:22:28,799] Trial 6 finished with value: 0.8500025078601375 and parameters: {'classifier__n_neighbors': 9}. Best is trial 3 with value: 0.8708393323014378.
[I 2025-03-16 16:22:28,833] Trial 7 finished with value: 0.8540614497948409 and parameters: {'classifier__n_neighbors': 8}. Best is trial 3 with value: 0.8708393323014378.
[I 2025-03-16 16:22:28,869] Trial 8 finished with value: 0.8540614497948409 and parameters: {'classifier__n_neighbors': 7}. Best is trial 3 with value: 0.8708393323014378.
[I 2025-03-16 16:22:28,904] Trial 9 finished with value: 0.8500025078601375 and parameters: {'classifier__n_neighbors': 9}. Best is trial 3 with value: 0.8708393323014378.
[I 2025-03-16 16:22:28,940] Trial 10 finished with value: 0.853757337534556 and parameters: {'classifier__n_neighbors': 5}. Best is trial 3 with value: 0.8708393323014378.
[I 2025-03-16 16:22:28,978] Trial 11 finished with value: 0.8708393323014378 and parameters: {'classifier__n_neighbors': 4}. Best is trial 3 with value: 0.8708393323014378.
[I 2025-03-16 16:22:29,018] Trial 12 finished with value: 0.8708393323014378 and parameters: {'classifier__n_neighbors': 4}. Best is trial 3 with value: 0.8708393323014378.
[I 2025-03-16 16:22:29,064] Trial 13 finished with value: 0.8708393323014378 and parameters: {'classifier__n_neighbors': 4}. Best is trial 3 with value: 0.8708393323014378.
[I 2025-03-16 16:22:29,110] Trial 14 finished with value: 0.8644490499806544 and parameters: {'classifier__n_neighbors': 6}. Best is trial 3 with value: 0.8708393323014378.
[I 2025-03-16 16:22:29,150] Trial 15 finished with value: 0.852472535627216 and parameters: {'classifier__n_neighbors': 3}. Best is trial 3 with value: 0.8708393323014378.
[I 2025-03-16 16:22:29,187] Trial 16 finished with value: 0.8644490499806544 and parameters: {'classifier__n_neighbors': 6}. Best is trial 3 with value: 0.8708393323014378.
[I 2025-03-16 16:22:29,223] Trial 17 finished with value: 0.853757337534556 and parameters: {'classifier__n_neighbors': 5}. Best is trial 3 with value: 0.8708393323014378.
[I 2025-03-16 16:22:29,258] Trial 18 finished with value: 0.852472535627216 and parameters: {'classifier__n_neighbors': 3}. Best is trial 3 with value: 0.8708393323014378.
[I 2025-03-16 16:22:29,301] Trial 19 finished with value: 0.853757337534556 and parameters: {'classifier__n_neighbors': 5}. Best is trial 3 with value: 0.8708393323014378.
[I 2025-03-16 16:22:29,302] A new study created in memory with name: no-name-661ea54c-6016-4f95-95c1-14625c5c3ce3
[I 2025-03-16 16:22:29,338] Trial 0 finished with value: 0.8714266501616535 and parameters: {'classifier__max_depth': 5}. Best is trial 0 with value: 0.8714266501616535.
[I 2025-03-16 16:22:29,376] Trial 1 finished with value: 0.8602455368427602 and parameters: {'classifier__max_depth': 7}. Best is trial 0 with value: 0.8714266501616535.
[I 2025-03-16 16:22:29,409] Trial 2 finished with value: 0.8562111169026421 and parameters: {'classifier__max_depth': 7}. Best is trial 0 with value: 0.8714266501616535.
[I 2025-03-16 16:22:29,438] Trial 3 finished with value: 0.8660426382920356 and parameters: {'classifier__max_depth': 8}. Best is trial 0 with value: 0.8714266501616535.
[I 2025-03-16 16:22:29,474] Trial 4 finished with value: 0.8602455368427602 and parameters: {'classifier__max_depth': 6}. Best is trial 0 with value: 0.8714266501616535.
[I 2025-03-16 16:22:29,500] Trial 5 finished with value: 0.8530791652774117 and parameters: {'classifier__max_depth': 7}. Best is trial 0 with value: 0.8714266501616535.
[I 2025-03-16 16:22:29,524] Trial 6 finished with value: 0.8543668744423588 and parameters: {'classifier__max_depth': 7}. Best is trial 0 with value: 0.8714266501616535.
[I 2025-03-16 16:22:29,546] Trial 7 finished with value: 0.8543668744423588 and parameters: {'classifier__max_depth': 7}. Best is trial 0 with value: 0.8714266501616535.
[I 2025-03-16 16:22:29,569] Trial 8 finished with value: 0.8503324545022405 and parameters: {'classifier__max_depth': 6}. Best is trial 0 with value: 0.8714266501616535.
[I 2025-03-16 16:22:29,592] Trial 9 finished with value: 0.8503324545022405 and parameters: {'classifier__max_depth': 9}. Best is trial 0 with value: 0.8714266501616535.
[I 2025-03-16 16:22:29,621] Trial 10 finished with value: 0.8653660441010474 and parameters: {'classifier__max_depth': 5}. Best is trial 0 with value: 0.8714266501616535.
[I 2025-03-16 16:22:29,650] Trial 11 finished with value: 0.8602455368427602 and parameters: {'classifier__max_depth': 9}. Best is trial 0 with value: 0.8714266501616535.
[I 2025-03-16 16:22:29,678] Trial 12 finished with value: 0.8602455368427602 and parameters: {'classifier__max_depth': 8}. Best is trial 0 with value: 0.8714266501616535.
[I 2025-03-16 16:22:29,705] Trial 13 finished with value: 0.8679715916915771 and parameters: {'classifier__max_depth': 5}. Best is trial 0 with value: 0.8714266501616535.
[I 2025-03-16 16:22:29,742] Trial 14 finished with value: 0.8624160361360216 and parameters: {'classifier__max_depth': 5}. Best is trial 0 with value: 0.8714266501616535.
[I 2025-03-16 16:22:29,775] Trial 15 finished with value: 0.8642602785963052 and parameters: {'classifier__max_depth': 5}. Best is trial 0 with value: 0.8714266501616535.
[I 2025-03-16 16:22:29,814] Trial 16 finished with value: 0.8562111169026421 and parameters: {'classifier__max_depth': 6}. Best is trial 0 with value: 0.8714266501616535.
[I 2025-03-16 16:22:29,849] Trial 17 finished with value: 0.8652259265696257 and parameters: {'classifier__max_depth': 5}. Best is trial 0 with value: 0.8714266501616535.
[I 2025-03-16 16:22:29,878] Trial 18 finished with value: 0.8543668744423588 and parameters: {'classifier__max_depth': 6}. Best is trial 0 with value: 0.8714266501616535.
[I 2025-03-16 16:22:29,909] Trial 19 finished with value: 0.8650439829094211 and parameters: {'classifier__max_depth': 5}. Best is trial 0 with value: 0.8714266501616535.
[I 2025-03-16 16:22:29,922] A new study created in memory with name: no-name-657ba4b1-604d-4538-8308-e92717fe2291
[I 2025-03-16 16:22:29,960] Trial 0 finished with value: 0.8541383838366302 and parameters: {'n_estimators': 3, 'max_features': 10}. Best is trial 0 with value: 0.8541383838366302.
[I 2025-03-16 16:22:30,003] Trial 1 finished with value: 0.8619654405188637 and parameters: {'n_estimators': 5, 'max_features': 4}. Best is trial 1 with value: 0.8619654405188637.
[I 2025-03-16 16:22:30,047] Trial 2 finished with value: 0.8519176665249955 and parameters: {'n_estimators': 5, 'max_features': 1}. Best is trial 1 with value: 0.8619654405188637.
[I 2025-03-16 16:22:30,098] Trial 3 finished with value: 0.8666940848208569 and parameters: {'n_estimators': 5, 'max_features': 5}. Best is trial 3 with value: 0.8666940848208569.
[I 2025-03-16 16:22:30,169] Trial 4 finished with value: 0.8484618117168523 and parameters: {'n_estimators': 12, 'max_features': 2}. Best is trial 3 with value: 0.8666940848208569.
[I 2025-03-16 16:22:30,227] Trial 5 finished with value: 0.8518784968309806 and parameters: {'n_estimators': 11, 'max_features': 9}. Best is trial 3 with value: 0.8666940848208569.
[I 2025-03-16 16:22:30,306] Trial 6 finished with value: 0.8568995793246295 and parameters: {'n_estimators': 13, 'max_features': 1}. Best is trial 3 with value: 0.8666940848208569.
[I 2025-03-16 16:22:30,368] Trial 7 finished with value: 0.850525129635734 and parameters: {'n_estimators': 10, 'max_features': 7}. Best is trial 3 with value: 0.8666940848208569.
[I 2025-03-16 16:22:30,396] Trial 8 finished with value: 0.8424702083957902 and parameters: {'n_estimators': 2, 'max_features': 10}. Best is trial 3 with value: 0.8666940848208569.
[I 2025-03-16 16:22:30,441] Trial 9 finished with value: 0.8619654405188637 and parameters: {'n_estimators': 5, 'max_features': 4}. Best is trial 3 with value: 0.8666940848208569.

StackingClassifier(estimators=[('lr',
                                Pipeline(steps=[('scaler', StandardScaler()),
                                                ('classifier',
                                                 LogisticRegression(C=5.551792776536298,
                                                                    max_iter=1000))])),
                               ('knn',
                                Pipeline(steps=[('scaler', StandardScaler()),
                                                ('classifier',
                                                 KNeighborsClassifier(n_neighbors=4))])),
                               ('dt',
                                Pipeline(steps=[('scaler', StandardScaler()),
                                                ('classifier',
                                                 DecisionTreeClassifier(max_depth=5))])),
                               ('rf',
                                RandomForestClassifier(max_features=4,
                                                       n_estimators=4,
                                                       random_state=100)),
                               ('boost',
                                GradientBoostingClassifier(learning_rate=0.2,
                                                           n_estimators=20))],
                   final_estimator=LogisticRegression())

In [100]:
train_predict = stacking_clf.predict(x_train)
test_predict = stacking_clf.predict(x_test)

print("F1-score (train):", f1_score(y_train, train_predict, average='macro'))
print("F1-score (test):", f1_score(y_test, test_predict, average='macro'))

F1-score (train): 0.9229998841541572
F1-score (test): 0.9018005110203692